### ISSUE TITLE
error during run

### ISSUE THREAD

**Issue by gijzelaerr** [ratt-ru/PyMORESANE#6]
```
Traceback (most recent call last):
  File "/home/andre/Software/install/bin/runsane", line 5, in <module>
    main()
  File "/usr/lib/python2.7/dist-packages/pymoresane/main.py", line 671, in main
    args.enforcepositivity, args.edgesuppression, args.edgeoffset)
  File "/usr/lib/python2.7/dist-packages/pymoresane/main.py", line 553, in moresane_by_scale
    edge_suppression=edge_suppression, edge_offset=edge_offset)
  File "/usr/lib/python2.7/dist-packages/pymoresane/main.py", line 140, in moresane
    psf_subregion_fft = conv.gpu_r2c_fft(psf_subregion, is_gpuarray=False, store_on_gpu=True)
  File "/usr/lib/python2.7/dist-packages/pymoresane/iuwt_convolution.py", line 98, in gpu_r2c_fft
    gpu_plan = Plan(gpu_in1.shape, np.float32, np.complex64)
NameError: global name 'Plan' is not defined
```

which comes from it can't import some modules

**Comment by JSKenyon** [comment]
Import error. Fixed.
